services:
  frontend:
    build: ./frontend
    command: npm run dev -- --host=0.0.0.0
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app

  backend:
    build: ./backend
    command: php artisan serve --host=0.0.0.0
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/www/html

